export const ADD_LOCATION = 'ADD_LOCATION'
export const SET_UNIT = 'SET_UNIT'
export const SET_LOCATION = 'SET_LOCATION'

export const REQUEST_CURRENT_WEATHER = 'REQUEST_CURRENT_WEATHER'
export const RECEIVE_CURRENT_WEATHER = 'RECEIVE_CURRENT_WEATHER'
export const REQUEST_FORECAST = 'REQUEST_FORECAST'
export const RECEIVE_LONG_FORECAST = 'RECEIVE_LONG_FORECAST'
export const RECEIVE_SHORT_FORECAST = 'RECEIVE_SHORT_FORECAST'
export const RECEIVED_ALL_DATA = 'RECEIVED_ALL_DATA'

export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE'