# [START runtime]
runtime: nodejs
vm: true
api_version: 1
# [END runtime]

# [START resources]
resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10
# [END resources]

# [START scaling]
manual_scaling:
  instances: 1
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 1
#  cool_down_period_sec: 60
#  cpu_utilization:
#    target_utilization: 0.5
# [END scaling]

env_variables:
  NODE_ENV: 'production'

# Temporary workaround for a Cloud SDK bug.
# Ensures that node_modules directory and any .log files are not uploaded (the
# other entries are the default values for skip_files). This will skip any Unix
# hidden files (such as the .git directory)
skip_files:
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - ^(.*/)?.*/node_modules/.*$
 - ^(.*/)?.*\.log$